# Generated by Django 4.2.20 on 2025-05-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='model_type',
            field=models.CharField(choices=[('LLM', 'Grand Modèle de Langage (LLM)'), ('IMG_GEN', 'Génération d\\images'), ('VOICE_GEN', 'Génération Vocale'), ('VISION', 'Vision par Ordinateur (GenAI)'), ('OTHER', 'Autre')], default='OTHER', help_text="Catégorie du modèle d'IA Générative", max_length=10),
        ),
    ]
