# Generated by Django 4.2.20 on 2025-05-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aimodel_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='model_type',
            field=models.CharField(choices=[('LLM', 'Grand Modèle de Langage (LLM)'), ('IMG_GEN', "Génération d'images"), ('VOICE_GEN', 'Génération Vocale'), ('VISION', 'Vision par Ordinateur (GenAI)'), ('OTHER', 'Autre')], default='OTHER', help_text="Catégorie du modèle d'IA Générative", max_length=10),
        ),
        migrations.CreateModel(
            name='FineTuningJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hyperparameters', models.JSONField(default=dict, help_text="Ex: {'lr': 0.001, 'epochs': 3, 'batch_size': 8}")),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('SUCCESS', 'Terminé avec succès'), ('FAILED', 'Échec')], default='PENDING', max_length=10)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('output_model_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine_tuning_jobs', to='api.dataset')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine_tuning_jobs', to='api.aimodel')),
            ],
        ),
    ]
