# Generated by Django 4.2.22 on 2025-06-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_aimodel_model_type_finetuningjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='upload_path',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
